### ISSUE TITLE
getting HTTPMovedPermanently error

### ISSUE THREAD

**Issue by jayceekay** [defunkt/gist#200]
```bash
justin@arrakis:~ $ brew uninstall gist
Uninstalling /usr/local/Cellar/gist/4.3.0...
justin@arrakis:~ $ brew install gist
==> Downloading https://github.com/defunkt/gist/archive/v4.3.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/gist-4.3.0.tar.gz
==> /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/rake install prefix=/usr/local/Cellar/gist/4.3.0
🍺  /usr/local/Cellar/gist/4.3.0: 4 files,  84K, built in 2 seconds
justin@arrakis:~ $ gist --login
Obtaining OAuth2 access_token from github.
GitHub username: jayceekay
GitHub password:
/usr/local/bin/gist:1576:in `block in login!': Got Net::HTTPMovedPermanently from gist:  (RuntimeError)
	from /usr/local/bin/gist:1534:in `loop'
	from /usr/local/bin/gist:1534:in `login!'
	from /usr/local/bin/gist:1821:in `block (2 levels) in <main>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/optparse.rb:1364:in `call'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/optparse.rb:1364:in `block in parse_in_order'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/optparse.rb:1351:in `catch'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/optparse.rb:1351:in `parse_in_order'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/optparse.rb:1345:in `order!'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/optparse.rb:1437:in `permute!'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/optparse.rb:1459:in `parse!'
	from /usr/local/bin/gist:1896:in `<main>'
```

**Comment by kodabb** [comment]
I have the exact same problem (both from homebrew and gem)

**Comment by velimir0xff** [comment]
make sure your GITHUB_URL has `https` scheme

**Comment by weakish** [comment]
Same error on `gist` installed with `gem`.

@velimir0xff  What the full value of `$GITHUB_URL`?
I used `https://github.com` and gist still gives the same error.

**Comment by velimir0xff** [comment]
@weakish if you're using public github, then you don't need to set `GITHUB_URL` variable (`https://api.github.com/` by default), everything should work out of box, though if you're trying to use privately hosted instance, then you need to specify url of your instance. For example: `https://github.example.com/`.
