### ISSUE TITLE
gist error when running certain commands using Termux

### ISSUE THREAD

**Issue by qntmpkts** [defunkt/gist#247]
Termux found at https://play.google.com/store/search?q=com.termux&c=apps (now runs with Android apps (ARC) on Chrome OS).

When running gist -l username, I get the following error:

    /data/data/com.termux/files/usr/lib/ruby/gems/2.3.0/gems/gist-4.5.0/lib/gist.rb:462:in `system': Function not implemented - getresuid(2) (Errno::ENOSYS)
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.3.0/gems/gist-4.5.0/lib/gist.rb:462:in `which'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.3.0/gems/gist-4.5.0/lib/gist.rb:523:in `legacy_private_gister?'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.3.0/gems/gist-4.5.0/lib/gist.rb:531:in `should_be_public?'
        from /data/data/com.termux/files/usr/lib/ruby/gems/2.3.0/gems/gist-4.5.0/bin/gist:153:in `<top (required)>'
        from /data/data/com.termux/files/usr/bin/gist:23:in `load'
        from /data/data/com.termux/files/usr/bin/gist:23:in `<main>'

![screenshot 2016-08-27 at 17 23 40](https://cloud.githubusercontent.com/assets/19355612/18030414/1e0e232c-6c7b-11e6-8ff2-8316947acd25.png)

**Comment by qntmpkts** [comment]
Most likely an issue with Termux. Closing.
