### ISSUE TITLE
One test failure in Ubuntu on all architectures

### ISSUE THREAD

**Issue by utkarsh2102** [defunkt/gist#331]
Hello @defunkt o/

Thanks for working on this! 🎉 

Whilst building this against ruby2.7 v2.7.3 on Ubuntu machines, one of the tests fail:
```
Failures:

  1) ... should be Net::HTTP when $HTTP_PROXY wasn't set
     Failure/Error: Gist.http_connection(FOO_URL).should be_an_instance_of(Net::HTTP)
       expected #<#<Class:0x000055a6ec1aa110> ddg.gg:80 open=false> to be an instance of Net::HTTP
     # ./spec/proxy_spec.rb:14:in `block (2 levels) in <top (required)>'
```

Complete build logs here: https://autopkgtest.ubuntu.com/results/autopkgtest-impish/impish/amd64/g/gist/20210516_212832_b0048@/log.gz

I am not sure what's causing this really, do you seem to have any idea about this?

**Comment by sabrina981** [comment]
> Hello @defunkt o/
> 
> Thanks for working on this! 🎉
> 
> Whilst building this against ruby2.7 v2.7.3 on Ubuntu machines, one of the tests fail:
> 
> ```
> Failures:
> 
>   1) ... should be Net::HTTP when $HTTP_PROXY wasn't set
>      Failure/Error: Gist.http_connection(FOO_URL).should be_an_instance_of(Net::HTTP)
>        expected #<#<Class:0x000055a6ec1aa110> ddg.gg:80 open=false> to be an instance of Net::HTTP
>      # ./spec/proxy_spec.rb:14:in `block (2 levels) in <top (required)>'
> ```
> 
> Complete build logs here: https://autopkgtest.ubuntu.com/results/autopkgtest-impish/impish/amd64/g/gist/20210516_212832_b0048@/log.gz
> 
> I am not sure what's causing this really, do you seem to have any idea about this?

I have to get my license in the bank accounts for internet access code to help

**Comment by luciferrc** [comment]
> Hello @defunkt o/
> 
> Thanks for working on this! 🎉
> 
> Whilst building this against ruby2.7 v2.7.3 on Ubuntu machines, one of the tests fail:
> 
> ```
> Failures:
> 
>   1) ... should be Net::HTTP when $HTTP_PROXY wasn't set
>      Failure/Error: Gist.http_connection(FOO_URL).should be_an_instance_of(Net::HTTP)
>        expected #<#<Class:0x000055a6ec1aa110> ddg.gg:80 open=false> to be an instance of Net::HTTP
>      # ./spec/proxy_spec.rb:14:in `block (2 levels) in <top (required)>'
> ```
> 
> Complete build logs here: https://autopkgtest.ubuntu.com/results/autopkgtest-impish/impish/amd64/g/gist/20210516_212832_b0048@/log.gz
> 
> I am not sure what's causing this really, do you seem to have any idea about this?

**Comment by 150616Angga1019** [comment]
#346

**Comment by Sittp** [comment]
https://github.com/defunkt/gist/issues/331#issue-893491581

**Comment by mohammadmn82** [comment]
>Mohammadmn82<

**Comment by Lucky777178** [comment]
> Hallo@defunkt
> 
> Vielen Dank für die Arbeit!
> 
> Während der Bau dieser gegen ruby2.7 v2.7.3 an Ubuntu Maschinen fehlschlägt einer der Tests:
> 
> ```
> Failures:
> 
>   1) ... should be Net::HTTP when $HTTP_PROXY wasn't set
>      Failure/Error: Gist.http_connection(FOO_URL).should be_an_instance_of(Net::HTTP)
>        expected #<#<Class:0x000055a6ec1aa110> ddg.gg:80 open=false> to be an instance of Net::HTTP
>      # ./spec/proxy_spec.rb:14:in `block (2 levels) in <top (required)>'
> ```
> 
> Vollständige Build-Protokolle hier: [https://autopkgtest.ubuntu.com/results/autopkgtest-impish/impish/amd64/g/gist/20210516-212832-b0048-log.gz](https://autopkgtest.ubuntu.com/results/autopkgtest-impish/impish/amd64/g/gist/20210516_212832_b0048@/log.gz)
> 
> Ich bin mir nicht sicher, was das wirklich verursacht, scheinen Sie eine Ahnung davon zu haben?

**Comment by anashope** [comment]
Failures:

  1) ... should be Net::HTTP when $HTTP_PROXY wasn't set
     Failure/Error: Gist.http_connection(FOO_URL).should be_an_instance_of(Net::HTTP)
       expected #<# anashop.com<Class:0x000055a6ec1aa110> ddg.gg:80 open=false> to be an instance of Net::HTTP
https//ww.metequen@meta.com
     # ./spec/proxy_spec.rb:14:in `block (2 levels) in <top (required)>'

**Comment by behnamdosti1189-lab** [comment]
URL /create

**Comment by txzzitxxx** [comment]
> Hello [@defunkt](https://github.com/defunkt) o/
> 
> Thanks for working on this! 🎉
> 
> Whilst building this against ruby2.7 v2.7.3 on Ubuntu machines, one of the tests fail:
> 
> ```
> Failures:
> 
>   1) ... should be Net::HTTP when $HTTP_PROXY wasn't set
>      Failure/Error: Gist.http_connection(FOO_URL).should be_an_instance_of(Net::HTTP)
>        expected #<#<Class:0x000055a6ec1aa110> ddg.gg:80 open=false> to be an instance of Net::HTTP
>      # ./spec/proxy_spec.rb:14:in `block (2 levels) in <top (required)>'
> ```
> 
> Complete build logs here: https://autopkgtest.ubuntu.com/results/autopkgtest-impish/impish/amd64/g/gist/20210516_212832_b0048@/log.gz
> 
> I am not sure what's causing this really, do you seem to have any idea about this?

https://github.com/defunkt/gist/issues/331
