### ISSUE TITLE
Can't establish creds

### ISSUE THREAD

**Issue by tbbooher** [defunkt/gist#332]
From a fresh install.

```
gist-paste --login
Obtaining OAuth2 access_token from github.
GitHub username: my_username
GitHub password:
Traceback (most recent call last):
        10: from /usr/bin/gist-paste:140:in `<main>'
         9: from /usr/lib/ruby/2.7.0/optparse.rb:1691:in `parse!'
         8: from /usr/lib/ruby/2.7.0/optparse.rb:1666:in `permute!'
         7: from /usr/lib/ruby/2.7.0/optparse.rb:1569:in `order!'
         6: from /usr/lib/ruby/2.7.0/optparse.rb:1575:in `parse_in_order'
         5: from /usr/lib/ruby/2.7.0/optparse.rb:1575:in `catch'
         4: from /usr/lib/ruby/2.7.0/optparse.rb:1589:in `block in parse_in_order'
         3: from /usr/bin/gist-paste:57:in `block (2 levels) in <main>'
         2: from /usr/lib/ruby/vendor_ruby/gist.rb:350:in `login!'
         1: from /usr/lib/ruby/vendor_ruby/gist.rb:350:in `loop'
/usr/lib/ruby/vendor_ruby/gist.rb:390:in `block in login!': Got Net::HTTPNotFound from gist: {"message":"Not Found","documentation_url":"https://docs.github.com/rest"} (RuntimeError)
```

**Comment by ConradIrwin** [comment]
Hey Tim, you’ll need to upgrade to gist v6.0.0 or greater which uses
Github’s new authentication scheme

Sent via Superhuman iOS ***@***.***>

**Comment by jacobvanorder** [comment]
What if you have enterprise github? Changing the url via `export GITHUB_URL=` forces the new way.
