### ISSUE TITLE
Received this error trying to login

### ISSUE THREAD

**Issue by bonelifer** [defunkt/gist#356]
OS: Xubuntu 22.04
```
gist-paste --login
Requesting login parameters...
/usr/lib/ruby/vendor_ruby/gist.rb:356:in `device_flow_login!': HTTP 404: {"error":"Not Found"} (RuntimeError)
	from /usr/lib/ruby/vendor_ruby/gist.rb:338:in `login!'
	from /usr/bin/gist-paste:57:in `block (2 levels) in <main>'
	from /usr/lib/ruby/3.0.0/optparse.rb:1591:in `block in parse_in_order'
	from /usr/lib/ruby/3.0.0/optparse.rb:1577:in `catch'
	from /usr/lib/ruby/3.0.0/optparse.rb:1577:in `parse_in_order'
	from /usr/lib/ruby/3.0.0/optparse.rb:1571:in `order!'
	from /usr/lib/ruby/3.0.0/optparse.rb:1668:in `permute!'
	from /usr/lib/ruby/3.0.0/optparse.rb:1693:in `parse!'
	from /usr/bin/gist-paste:140:in `<main>'
```

**Comment by christianlantin** [comment]
Master
